services:
  - type: web
    name: growthproai-frontend
    env: static
    buildCommand: npm install && NODE_ENV=production npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://growthproai-backendpart.onrender.com
      - key: NODE_VERSION
        value: 22.14.0
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache