services:
  - type: web
    name: growthproai-frontend-03
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: "22.14.0"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache